import type { User, Community, Post, Conversation, Message, Notification, Connection, RecommendedUser, AdminStats, Report } from './types';

export const currentUser: User = {
  id: 'user-1',
  email: 'john.doe@example.com',
  name: 'John Doe',
  username: 'johndoe',
  avatar: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=150&h=150&fit=crop&crop=face',
  bio: 'Software developer passionate about building connections and exploring new technologies.',
  location: 'San Francisco, CA',
  interests: ['Technology', 'Photography', 'Hiking', 'Reading', 'Music'],
  goals: ['Learn new skills', 'Network with professionals', 'Find mentorship'],
  joinedAt: '2024-01-15T10:00:00Z',
  isOnline: true,
  lastActive: new Date().toISOString(),
  connectionsCount: 127,
  communitiesCount: 8,
  role: 'user',
  isVerified: true,
  privacySettings: {
    profileVisibility: 'public',
    showOnlineStatus: true,
    allowMessages: 'everyone',
    showLocation: true,
  },
};

export const mockUsers: User[] = [
  {
    id: 'user-2',
    email: 'sarah.wilson@example.com',
    name: 'Sarah Wilson',
    username: 'sarahw',
    avatar: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=150&h=150&fit=crop&crop=face',
    bio: 'UX Designer | Coffee enthusiast | Always learning',
    location: 'New York, NY',
    interests: ['Design', 'Photography', 'Travel', 'Coffee'],
    goals: ['Build design portfolio', 'Connect with creatives'],
    joinedAt: '2024-02-20T10:00:00Z',
    isOnline: true,
    lastActive: new Date().toISOString(),
    connectionsCount: 89,
    communitiesCount: 5,
    role: 'user',
    isVerified: true,
    privacySettings: {
      profileVisibility: 'public',
      showOnlineStatus: true,
      allowMessages: 'everyone',
      showLocation: true,
    },
  },
  {
    id: 'user-3',
    email: 'mike.chen@example.com',
    name: 'Mike Chen',
    username: 'mikechen',
    avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&h=150&fit=crop&crop=face',
    bio: 'Product Manager at TechCorp | Startup advisor',
    location: 'Austin, TX',
    interests: ['Technology', 'Startups', 'Gaming', 'Fitness'],
    goals: ['Mentor aspiring PMs', 'Build side projects'],
    joinedAt: '2024-01-05T10:00:00Z',
    isOnline: false,
    lastActive: '2024-03-14T18:30:00Z',
    connectionsCount: 234,
    communitiesCount: 12,
    role: 'user',
    isVerified: true,
    privacySettings: {
      profileVisibility: 'public',
      showOnlineStatus: true,
      allowMessages: 'connections',
      showLocation: true,
    },
  },
  {
    id: 'user-4',
    email: 'emily.johnson@example.com',
    name: 'Emily Johnson',
    username: 'emilyj',
    avatar: 'https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=150&h=150&fit=crop&crop=face',
    bio: 'Data Scientist | AI enthusiast | Speaker',
    location: 'Seattle, WA',
    interests: ['AI', 'Machine Learning', 'Reading', 'Yoga'],
    goals: ['Share knowledge', 'Collaborate on research'],
    joinedAt: '2024-03-01T10:00:00Z',
    isOnline: true,
    lastActive: new Date().toISOString(),
    connectionsCount: 156,
    communitiesCount: 7,
    role: 'user',
    isVerified: false,
    privacySettings: {
      profileVisibility: 'connections',
      showOnlineStatus: false,
      allowMessages: 'connections',
      showLocation: false,
    },
  },
  {
    id: 'user-5',
    email: 'david.kim@example.com',
    name: 'David Kim',
    username: 'davidk',
    avatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=150&h=150&fit=crop&crop=face',
    bio: 'Entrepreneur | Angel investor | Tech blogger',
    location: 'Los Angeles, CA',
    interests: ['Entrepreneurship', 'Investing', 'Technology', 'Travel'],
    goals: ['Find co-founders', 'Invest in startups'],
    joinedAt: '2023-12-10T10:00:00Z',
    isOnline: false,
    lastActive: '2024-03-13T22:00:00Z',
    connectionsCount: 412,
    communitiesCount: 15,
    role: 'user',
    isVerified: true,
    privacySettings: {
      profileVisibility: 'public',
      showOnlineStatus: true,
      allowMessages: 'everyone',
      showLocation: true,
    },
  },
  {
    id: 'user-6',
    email: 'lisa.martinez@example.com',
    name: 'Lisa Martinez',
    username: 'lisam',
    avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&h=150&fit=crop&crop=face',
    bio: 'Marketing strategist | Content creator | Dog mom',
    location: 'Chicago, IL',
    interests: ['Marketing', 'Social Media', 'Writing', 'Pets'],
    goals: ['Grow personal brand', 'Help small businesses'],
    joinedAt: '2024-02-01T10:00:00Z',
    isOnline: true,
    lastActive: new Date().toISOString(),
    connectionsCount: 198,
    communitiesCount: 9,
    role: 'user',
    isVerified: true,
    privacySettings: {
      profileVisibility: 'public',
      showOnlineStatus: true,
      allowMessages: 'everyone',
      showLocation: true,
    },
  },
];

export const mockCommunities: Community[] = [
  {
    id: 'comm-1',
    name: 'Tech Innovators',
    description: 'A community for tech enthusiasts to discuss the latest trends, share projects, and collaborate on innovative ideas.',
    category: 'Technology',
    avatar: 'https://images.unsplash.com/photo-1518770660439-4636190af475?w=150&h=150&fit=crop',
    coverImage: 'https://images.unsplash.com/photo-1517694712202-14dd9538aa97?w=1200&h=400&fit=crop',
    memberCount: 2847,
    postCount: 1523,
    createdAt: '2023-06-15T10:00:00Z',
    createdBy: 'user-3',
    isPrivate: false,
    rules: ['Be respectful', 'No spam', 'Stay on topic', 'Share knowledge freely'],
    admins: ['user-3', 'user-5'],
    isMember: true,
  },
  {
    id: 'comm-2',
    name: 'Design Hub',
    description: 'Connect with designers from around the world. Share your work, get feedback, and stay updated on design trends.',
    category: 'Design',
    avatar: 'https://images.unsplash.com/photo-1561070791-2526d30994b5?w=150&h=150&fit=crop',
    coverImage: 'https://images.unsplash.com/photo-1558655146-9f40138edfeb?w=1200&h=400&fit=crop',
    memberCount: 1654,
    postCount: 892,
    createdAt: '2023-08-20T10:00:00Z',
    createdBy: 'user-2',
    isPrivate: false,
    rules: ['Constructive feedback only', 'Credit original creators', 'No AI-generated art without disclosure'],
    admins: ['user-2'],
    isMember: true,
  },
  {
    id: 'comm-3',
    name: 'Startup Founders',
    description: 'A private community for startup founders to share experiences, seek advice, and find potential partners.',
    category: 'Business',
    avatar: 'https://images.unsplash.com/photo-1559136555-9303baea8ebd?w=150&h=150&fit=crop',
    coverImage: 'https://images.unsplash.com/photo-1553877522-43269d4ea984?w=1200&h=400&fit=crop',
    memberCount: 543,
    postCount: 421,
    createdAt: '2023-09-10T10:00:00Z',
    createdBy: 'user-5',
    isPrivate: true,
    rules: ['Verify founder status', 'Maintain confidentiality', 'Support fellow founders'],
    admins: ['user-5'],
    isMember: false,
  },
  {
    id: 'comm-4',
    name: 'Photography Enthusiasts',
    description: 'Share your photos, learn new techniques, and connect with fellow photography lovers.',
    category: 'Photography',
    avatar: 'https://images.unsplash.com/photo-1502920917128-1aa500764cbd?w=150&h=150&fit=crop',
    coverImage: 'https://images.unsplash.com/photo-1452587925148-ce544e77e70d?w=1200&h=400&fit=crop',
    memberCount: 3201,
    postCount: 2156,
    createdAt: '2023-05-01T10:00:00Z',
    createdBy: 'user-2',
    isPrivate: false,
    rules: ['Only post original content', 'Provide constructive criticism', 'Tag NSFW content'],
    admins: ['user-2', 'user-6'],
    isMember: true,
  },
  {
    id: 'comm-5',
    name: 'AI & Machine Learning',
    description: 'Discuss AI developments, share research papers, and collaborate on ML projects.',
    category: 'Technology',
    avatar: 'https://images.unsplash.com/photo-1677442136019-21780ecad995?w=150&h=150&fit=crop',
    coverImage: 'https://images.unsplash.com/photo-1620712943543-bcc4688e7485?w=1200&h=400&fit=crop',
    memberCount: 1892,
    postCount: 967,
    createdAt: '2023-11-05T10:00:00Z',
    createdBy: 'user-4',
    isPrivate: false,
    rules: ['Cite sources', 'No misinformation', 'Respect different perspectives'],
    admins: ['user-4'],
    isMember: true,
  },
];

export const mockPosts: Post[] = [
  {
    id: 'post-1',
    communityId: 'comm-1',
    authorId: 'user-3',
    author: mockUsers.find(u => u.id === 'user-3'),
    content: 'Just finished building a real-time collaboration tool using WebRTC and React. The latency is incredibly low! Happy to share insights with anyone interested in building similar projects.',
    images: ['https://images.unsplash.com/photo-1517694712202-14dd9538aa97?w=800&h=400&fit=crop'],
    likesCount: 47,
    commentsCount: 12,
    createdAt: '2024-03-14T09:30:00Z',
    isLiked: false,
  },
  {
    id: 'post-2',
    communityId: 'comm-2',
    authorId: 'user-2',
    author: mockUsers.find(u => u.id === 'user-2'),
    content: 'New design system just dropped! After 3 months of work, our team has created a comprehensive design system with 200+ components. Check out the link in comments.',
    images: ['https://images.unsplash.com/photo-1558655146-9f40138edfeb?w=800&h=400&fit=crop'],
    likesCount: 89,
    commentsCount: 23,
    createdAt: '2024-03-14T08:15:00Z',
    isLiked: true,
  },
  {
    id: 'post-3',
    communityId: 'comm-5',
    authorId: 'user-4',
    author: mockUsers.find(u => u.id === 'user-4'),
    content: 'Fascinating paper on emergent behavior in large language models. The researchers found that certain capabilities only appear after reaching specific parameter thresholds. This has huge implications for AI scaling.',
    likesCount: 156,
    commentsCount: 45,
    createdAt: '2024-03-13T22:00:00Z',
    isLiked: false,
  },
  {
    id: 'post-4',
    communityId: 'comm-4',
    authorId: 'user-6',
    author: mockUsers.find(u => u.id === 'user-6'),
    content: 'Golden hour at the Grand Canyon. Sometimes you just need to stop and appreciate the beauty around us.',
    images: [
      'https://images.unsplash.com/photo-1474044159687-1ee9f3a51722?w=800&h=400&fit=crop',
      'https://images.unsplash.com/photo-1615551043360-33de8b5f410c?w=800&h=400&fit=crop',
    ],
    likesCount: 234,
    commentsCount: 31,
    createdAt: '2024-03-13T19:45:00Z',
    isLiked: true,
  },
  {
    id: 'post-5',
    authorId: 'user-5',
    author: mockUsers.find(u => u.id === 'user-5'),
    content: 'Looking for a technical co-founder for a B2B SaaS idea in the sustainability space. If you are passionate about climate tech and have full-stack experience, let us connect!',
    likesCount: 67,
    commentsCount: 18,
    createdAt: '2024-03-13T14:20:00Z',
    isLiked: false,
  },
];

export const mockConversations: Conversation[] = [
  {
    id: 'conv-1',
    participants: [currentUser, mockUsers[0]],
    lastMessage: {
      id: 'msg-1',
      conversationId: 'conv-1',
      senderId: 'user-2',
      content: 'That sounds great! Let me know when you are free to discuss the design.',
      createdAt: '2024-03-14T10:30:00Z',
      isRead: false,
    },
    unreadCount: 2,
    createdAt: '2024-03-10T10:00:00Z',
    updatedAt: '2024-03-14T10:30:00Z',
  },
  {
    id: 'conv-2',
    participants: [currentUser, mockUsers[1]],
    lastMessage: {
      id: 'msg-2',
      conversationId: 'conv-2',
      senderId: 'user-1',
      content: 'Thanks for the product feedback! I will share it with the team.',
      createdAt: '2024-03-13T16:45:00Z',
      isRead: true,
    },
    unreadCount: 0,
    createdAt: '2024-03-08T14:00:00Z',
    updatedAt: '2024-03-13T16:45:00Z',
  },
  {
    id: 'conv-3',
    participants: [currentUser, mockUsers[2]],
    lastMessage: {
      id: 'msg-3',
      conversationId: 'conv-3',
      senderId: 'user-4',
      content: 'Here is the research paper I mentioned. Let me know your thoughts!',
      createdAt: '2024-03-12T09:15:00Z',
      isRead: true,
    },
    unreadCount: 0,
    createdAt: '2024-03-05T11:00:00Z',
    updatedAt: '2024-03-12T09:15:00Z',
  },
];

export const mockMessages: Record<string, Message[]> = {
  'conv-1': [
    {
      id: 'msg-1-1',
      conversationId: 'conv-1',
      senderId: 'user-1',
      content: 'Hi Sarah! I loved your recent design work. Would you be interested in collaborating on a project?',
      createdAt: '2024-03-14T09:00:00Z',
      isRead: true,
    },
    {
      id: 'msg-1-2',
      conversationId: 'conv-1',
      senderId: 'user-2',
      content: 'Hey John! Thanks so much! I would love to hear more about what you have in mind.',
      createdAt: '2024-03-14T09:15:00Z',
      isRead: true,
    },
    {
      id: 'msg-1-3',
      conversationId: 'conv-1',
      senderId: 'user-1',
      content: 'I am working on a new app that needs a complete UI overhaul. Your style would be perfect for it.',
      createdAt: '2024-03-14T09:30:00Z',
      isRead: true,
    },
    {
      id: 'msg-1-4',
      conversationId: 'conv-1',
      senderId: 'user-2',
      content: 'That sounds great! Let me know when you are free to discuss the design.',
      createdAt: '2024-03-14T10:30:00Z',
      isRead: false,
    },
  ],
  'conv-2': [
    {
      id: 'msg-2-1',
      conversationId: 'conv-2',
      senderId: 'user-3',
      content: 'Hey, I had some thoughts on the product roadmap we discussed.',
      createdAt: '2024-03-13T15:00:00Z',
      isRead: true,
    },
    {
      id: 'msg-2-2',
      conversationId: 'conv-2',
      senderId: 'user-1',
      content: 'Sure, I would love to hear your feedback!',
      createdAt: '2024-03-13T15:30:00Z',
      isRead: true,
    },
    {
      id: 'msg-2-3',
      conversationId: 'conv-2',
      senderId: 'user-3',
      content: 'I think we should prioritize the mobile experience first. User research shows 70% of our users are on mobile.',
      createdAt: '2024-03-13T16:00:00Z',
      isRead: true,
    },
    {
      id: 'msg-2-4',
      conversationId: 'conv-2',
      senderId: 'user-1',
      content: 'Thanks for the product feedback! I will share it with the team.',
      createdAt: '2024-03-13T16:45:00Z',
      isRead: true,
    },
  ],
};

export const mockNotifications: Notification[] = [
  {
    id: 'notif-1',
    userId: 'user-1',
    type: 'connection_request',
    title: 'New Connection Request',
    message: 'Emily Johnson wants to connect with you',
    isRead: false,
    createdAt: '2024-03-14T11:00:00Z',
    data: { userId: 'user-4' },
  },
  {
    id: 'notif-2',
    userId: 'user-1',
    type: 'message',
    title: 'New Message',
    message: 'Sarah Wilson sent you a message',
    isRead: false,
    createdAt: '2024-03-14T10:30:00Z',
    data: { conversationId: 'conv-1' },
  },
  {
    id: 'notif-3',
    userId: 'user-1',
    type: 'post_like',
    title: 'Post Liked',
    message: 'Mike Chen liked your post',
    isRead: true,
    createdAt: '2024-03-14T09:00:00Z',
    data: { postId: 'post-1' },
  },
  {
    id: 'notif-4',
    userId: 'user-1',
    type: 'community_invite',
    title: 'Community Invitation',
    message: 'You have been invited to join Startup Founders',
    isRead: true,
    createdAt: '2024-03-13T18:00:00Z',
    data: { communityId: 'comm-3' },
  },
];

export const mockConnections: Connection[] = [
  {
    id: 'conn-1',
    userId: 'user-1',
    connectedUserId: 'user-2',
    status: 'accepted',
    createdAt: '2024-03-10T10:00:00Z',
    user: mockUsers[0],
  },
  {
    id: 'conn-2',
    userId: 'user-1',
    connectedUserId: 'user-3',
    status: 'accepted',
    createdAt: '2024-03-08T14:00:00Z',
    user: mockUsers[1],
  },
  {
    id: 'conn-3',
    userId: 'user-4',
    connectedUserId: 'user-1',
    status: 'pending',
    createdAt: '2024-03-14T11:00:00Z',
    user: mockUsers[2],
  },
  {
    id: 'conn-4',
    userId: 'user-1',
    connectedUserId: 'user-6',
    status: 'accepted',
    createdAt: '2024-03-05T09:00:00Z',
    user: mockUsers[4],
  },
];

export const mockRecommendedUsers: RecommendedUser[] = [
  {
    ...mockUsers[2],
    matchScore: 92,
    sharedInterests: ['AI', 'Technology', 'Reading'],
    mutualConnections: 5,
  },
  {
    ...mockUsers[3],
    matchScore: 87,
    sharedInterests: ['Technology', 'Startups'],
    mutualConnections: 8,
  },
  {
    ...mockUsers[4],
    matchScore: 78,
    sharedInterests: ['Photography', 'Travel'],
    mutualConnections: 3,
  },
];

export const mockAdminStats: AdminStats = {
  totalUsers: 15847,
  activeUsers: 8932,
  totalCommunities: 234,
  totalMessages: 892456,
  totalConnections: 45678,
  reportedContent: 23,
  newUsersToday: 156,
  newUsersThisWeek: 892,
};

export const mockReports: Report[] = [
  {
    id: 'report-1',
    reporterId: 'user-2',
    reportedUserId: 'user-7',
    reason: 'Spam',
    description: 'This user is sending unsolicited promotional messages to multiple users.',
    status: 'pending',
    createdAt: '2024-03-14T08:00:00Z',
  },
  {
    id: 'report-2',
    reporterId: 'user-3',
    reportedPostId: 'post-10',
    reason: 'Inappropriate Content',
    description: 'This post contains misleading information about investment opportunities.',
    status: 'reviewed',
    createdAt: '2024-03-13T14:30:00Z',
  },
  {
    id: 'report-3',
    reporterId: 'user-4',
    reportedCommunityId: 'comm-8',
    reason: 'Harassment',
    description: 'Community members are engaging in coordinated harassment of other users.',
    status: 'pending',
    createdAt: '2024-03-12T20:00:00Z',
  },
];

export const interestOptions = [
  'Technology', 'Design', 'Photography', 'Travel', 'Music', 'Sports', 'Gaming',
  'Reading', 'Writing', 'Cooking', 'Fitness', 'Art', 'Movies', 'Science',
  'Business', 'Marketing', 'Finance', 'Entrepreneurship', 'AI', 'Machine Learning',
  'Web Development', 'Mobile Development', 'Data Science', 'Cybersecurity',
  'Blockchain', 'Sustainability', 'Health', 'Education', 'Psychology', 'Philosophy'
];

export const goalOptions = [
  'Learn new skills', 'Network with professionals', 'Find mentorship',
  'Build side projects', 'Start a business', 'Find co-founders',
  'Share knowledge', 'Get career advice', 'Collaborate on research',
  'Grow personal brand', 'Find job opportunities', 'Invest in startups',
  'Make new friends', 'Join communities', 'Explore hobbies'
];
